version: '3.8'

services:
  weatherapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=8080
      
      # API Configuration - Replace with your actual values
      - VITE_OPENAI_API_URL=${VITE_OPENAI_API_URL:-https://api.openai.com/v1/chat/completions}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_WEATHER_API_URL=${VITE_WEATHER_API_URL:-https://api.openweathermap.org/data/2.5/weather}
      - VITE_WEATHER_API_KEY=${VITE_WEATHER_API_KEY}
    
    # Optional: Use .env file
    env_file:
      - .env
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M 